### ISSUE TITLE
не просматривает 3mf

### ISSUE THREAD

**Issue by lwfl** [questfulcat/SolidModelBrowser#1]
не просматривает 3mf Например этот https://cloud.mail.ru/public/w3La/niMsVrJKn

**Comment by questfulcat** [comment]
Пока реализована загрузка только основной модели, геометрия которой хранится в 3D/3dmodel.model файле внутри контейнера 3MF. Загрузка составных моделей пока ещё не реализована. Это указано в readme.

**Comment by JCU0** [comment]
### 3MF "слипается".
По-видимому, не учитываются относительные смещения различных моделей внутри 3MF. Модели внутри составного 3MF располагаются в начале координат и накладываются друг на друга.

### Сглаживание/нормали не работают.
* Программа пытается нарисовать прямые углы сглаженными. Кубик выглядит, как низкополигональная пародия на сферу.
* Треугольники, лежащие на модели в одной плоскости, выглядят, как мятая фольга.
* Кнопка пересчёта нормалей не поогает, ничего не меняется при нажатии.

Предлагаю сделать кнопку, отключающую сглаживание. Либо, если возможно, отключать сглаживание между гранями с углом более, например, 15 градусов между нормалями.

**Comment by questfulcat** [comment]
- В программе нет сглаживания геометрии моделей.
- Пересчёт нормалей влияет только на освещение полигонов.
- Загружается ровно то, что прописано в качестве основной модели в 3D/3dmodel.model внутри 3MF.
- Отладка импорта 3MF проводилась на файлах, сохранённых из слайсера Cura. Более функциональный импорт 3MF, возможно, будет реализован в следующих версиях.

**Comment by JCU0** [comment]
Речь идёт как раз о некорректном освещении полигонов. Отсутствуют чёткие грани, вся модель выглядит гладкой и мятой.
Вот пример, как сейчас выглядит шайба в 3MF.
![1](https://github.com/user-attachments/assets/6ac97d86-273c-44a5-ac12-39722435f9b5)

**Comment by questfulcat** [comment]
в версии 0.2 класс импорта 3MF переделан

**Comment by questfulcat** [comment]
У объекта модели не указана матрица трансформации. В следующей версии будет использоваться матрица по-умолчанию в таких случаях.

**Comment by questfulcat** [comment]
- исправления импорта 3MF внесены в версии 0.3
- для исправления нечётких граней модели используйте Recreate unsmoothed [CTRL+F]

**Comment by questfulcat** [comment]
В версии 0.3.1 улучшена поддержка 3MF
