### ISSUE TITLE
Не раскрывается на полный экран

### ISSUE THREAD

**Issue by JCU0** [questfulcat/SolidModelBrowser#2]
### Не работает максимизация окна двойным кликом по заголовку.
Стандартно в WIndows можно разворачивать окна двойным кликом по заголовку. Здесь эта возможность не реализована, необходимо целиться в кнопку в углу окна.

### Окно разворачивается не на весь экран.
Окно не удаётся развернуть на весь экран, максимальный размер ограничен. У меня ноутбук с дополнительным монитором большего разрешения, чем его штатный экран. Условно, 720p разрешение штатного монитора, 1080p разрешение дополнительного монитора. При попытке развернуть окно на дополнительном мониторе (1080), оно упирается, по-видимому, в разрешение основного монитора (720).

### P.S.
Программа для меня уже полезная, хотя и достаточно сырая. Планирую пользоваться, т.к. тоже имею несколько сотен STL файлов и подыскивал удобный просмотрщик для навигации по ним. Спасибо.

**Comment by questfulcat** [comment]
Попробуйте закомментировать строку 34 в MainWindow.xaml.cs:
MaxHeight = SystemParameters.MaximizedPrimaryScreenHeight; // to avoid taskbar overlay
но это может привести к перекрытию таскбара

разворачивание окна по двойному клику по заголовку ещё не реализовано

**Comment by questfulcat** [comment]
- механизм расчёта максимального размера окна изменён
- в случае неправильного расчёта максимального размера окна для неосновного дисплея, можно выставить параметры максимального размера окна в настройках приложения вручную (MaxWidth, MaxHeight)

**Comment by questfulcat** [comment]
нажмите C для поворота камеры на центр модели
