### ISSUE TITLE
[req] Выделение ребер

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [questfulcat/SolidModelBrowser#5]
Выделение ребер. Rhinoceros 3D как-то это делает: 
https://i.imgur.com/TLrHmDL.png
https://i.imgur.com/3gf0Cfq.png
https://www.upload.ee/files/17297069/test.zip.html

**Comment by questfulcat** [comment]
Каркасный режим (wireframe) в ближайшее время не планируется. Для улучшения просмотра мелких выступов попробуйте отключить диффузный материал [F2].
