### ISSUE TITLE
[req] показ сетки

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [questfulcat/SolidModelBrowser#6]
Ползунок контраста/непрозрачности сетки. На минимуме сетка не видна.

**Comment by questfulcat** [comment]
в версии 0.3 полигон ground выполняет роль сетки

**Comment by questfulcat** [comment]
Каркасный режим (wireframe) пока не знаю как реализовать.

**Comment by questfulcat** [comment]
добавил каркасный режим
