### ISSUE TITLE
Синие STL

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [questfulcat/SolidModelBrowser#8]
https://www.thingiverse.com/thing:5406692/files
PetamentorLogo_-_flashlit123.stl показывает желтым (как обычно), а остальные - синие: https://i.imgur.com/Jw0HMCV.png

https://www.thingiverse.com/thing:6090725/files
Тут большая часть желтые (например Cutter-Capot_moteur.stl); On_OFF_switch.stl из синих.

**Comment by questfulcat** [comment]
Видимо, файл содержит данные нормалей, но они некорректные. Нажмите кнопку Remove original model normals для решения проблемы.

**Comment by questfulcat** [comment]
Обратная сторона отличается от наружной порядком определения вершин треугольника, по часовой/против часовой стрелки. Нормали влияют на отражение освещения треугольника, но при их отсутствии считаются перпендикулярными.

Возможно, добавлю настройку, разрешающую игнорировать оригинальные нормали, в следующих версиях.

**Comment by questfulcat** [comment]
добавил настройку в версии 0.4
